server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expenses_db
    username: postgres
    password: julianr
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect=org:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQL81Dialect